name: FastAPI Test

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/
    strategy:
      matrix:
        python-version: [3.9]
    env:
      MODE: "dev"

    steps:
      - uses: actions/checkout@v2
      - name: Iniciando python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Instalando dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Executando testes
        run: |
          pytest
